"""add total comments

Revision ID: 56494012f2e6
Revises: c134e8529443
Create Date: 2023-07-30 17:05:14.092324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56494012f2e6'
down_revision = 'c134e8529443'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('total_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'total_comments')
    # ### end Alembic commands ###
