"""add favorite ads

Revision ID: 690401545fea
Revises: 56494012f2e6
Create Date: 2023-07-31 20:10:13.545095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690401545fea'
down_revision = '56494012f2e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_ads',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index(op.f('ix_favorite_ads_row_id'), 'favorite_ads', ['row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_ads_row_id'), table_name='favorite_ads')
    op.drop_table('favorite_ads')
    # ### end Alembic commands ###
